// <auto-generated />
using CatsAndPlants.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatsAndPlants.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatsAndPlants.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BillPostal")
                        .HasColumnType("int");

                    b.Property<string>("BillState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipPostal")
                        .HasColumnType("int");

                    b.Property<string>("ShipState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BillAddress = "123 North",
                            BillCity = "Phoenix",
                            BillPostal = 52234,
                            BillState = "AZ",
                            Email = "c@c.com",
                            FirstName = "Charlies",
                            LastName = "Avocado",
                            Password = "Shnock123",
                            Phone = "111-111-1111",
                            ShipAddress = "123 North",
                            ShipCity = "Phoenix",
                            ShipPostal = 52234,
                            ShipState = "AZ"
                        },
                        new
                        {
                            CustomerId = 2,
                            BillAddress = "123 North",
                            BillCity = "Phoenix",
                            BillPostal = 52234,
                            BillState = "AZ",
                            Email = "J@N.com",
                            FirstName = "Josephina",
                            LastName = "Navarro",
                            Password = "Shnock123",
                            Phone = "222-222-2222",
                            ShipAddress = "456 South",
                            ShipCity = "Flagstaff",
                            ShipPostal = 52233,
                            ShipState = "AZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
